use master

SELECT DB.DATABASE_ID         AS [DB_ID],
       DB.NAME                AS [DB_NAME],
       DB.COMPATIBILITY_LEVEL AS [DB_COMPATIBILITY],
       DB.COLLATION_NAME      AS [DB_COLLATION],
       FL.NAME                AS [FILE_LOG_NAME]
  FROM SYS.DATABASES DB(NOLOCK)
       INNER JOIN SYS.MASTER_FILES FL (NOLOCK)
         ON FL.DATABASE_ID = DB.DATABASE_ID
 WHERE DB.NAME NOT IN ( 'MASTER', 'TEMPDB', 'MODEL', 'MSDB' )
   AND DB.STATE = 0
   AND FL.TYPE = 1
 ORDER BY DB.NAME 



